### ISSUE TITLE
Getting the hydration shell between SAS and SES?

### ISSUE THREAD

**Issue by johnnytam100** [UnixJunkie/EDTSurf#5]
Hi EDTSurf author!
Do you know if it is possible to use EDTSurf to extract a triangular mesh that encloses the hydration shell between SAS and SES?
Thanks in advance!

**Comment by UnixJunkie** [comment]
The EDTSurf authors contact info should be over there: https://zhanglab.ccmb.med.umich.edu/EDTSurf/
